### ISSUE TITLE
as6809: lbsr issue

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Bintools#4]
I'm compiling the FUZIX `cpp` with the current compiler, 6809 backend + bintools. When I run it, it crashes. The debug output shows:

```
     _gettok+018D: LDU #$0000       | -FHI-Z-- 66:00 66D0 0000 0000 FD64
     _gettok+0190: STD 4,S          | -FHI---- 66:00 66D0 0000 0000 FD64
     _gettok+0192: STD 2,S          | -FHI---- 66:00 66D0 0000 0000 FD64
     _gettok+0194: LBSR $0A8D       | -FHI---- 66:00 66D0 0000 0000 FD62
      _pgetc+0000: LEAS 14,S        | -FHI---- 66:00 66D0 0000 0000 FD70
      _pgetc+0002: PULS PC,U        | -FHI---- 66:00 66D0 0000 6105 FD74
0000: NEG <$00         | -FHI-Z-- 66:00 66D0 0000 6105 FD74
0002: NEG <$00         | -FHI-Z-- 66:00 66D0 0000 6105 FD74
```

Now, the assembly code for `pgetc()` is:

```
L17_r:
        leas 14,s                     <== We are lbsr'ing here, but
        puls u,pc
        .export _pgetc
_pgetc:
        pshs u                           <=== pgetc starts here
        leas -2,s
;
```

So it looks like `as6809` is incorrectly calculating the `lbsr` jump value.

I've added `cpp` to [Fuzemsys](https://github.com/DoctorWkt/Fuzemsys/tree/main/cmds/cpp) if you want to have a look.

**Comment by EtchedPixels** [comment]
Load time value is 07CB which looks wrong
Assembler output is a segment reloc for 0960 which is correct (two bytes displaced as the cpu calculates the address from the byte after the two bytes of relative offset)
